language: python
python:
  - "2.7"
install:
  - pip install -U pytest pylibacl setuptools
  - python setup.py build
  - python setup.py install
script: PYTHONPATH="." py.test
# needed by pylibacl
addons:
  apt:
    packages:
      - libacl1-dev
      - libusb-1.0-0-dev
